# Detection de motifs


## Algorithmes Randomisés.


In [1]:
import random
import numpy as np

nuc = ('A', 'C', 'G', 'T')

k=7 #taille de motif
v=4 #nb de positions variable dans le motif
t=20 #nb de sequences
n=50 #longuer des sequence

sequence_exemple=[]

def generateRandomSequence(n):
    return random.choices(["A","T","G","C"],weights =[1,1,1,1],k=n)

def generateRandomSequences(n, t):
    return [generateRandomSequence(n) for k in range(0,t)]

def generateMotif(k,v):
    
    motif=random.choices(["A","T","G","C"],weights =[1,1,1,1],k=k)
    
    dico_rand={0:"A",1:"T",2:"G",3:"C"}
    
    
    for i in range(0,v):
        motif[int(random.uniform(0,len(motif)))]=dico_rand[int(random.uniform(0,4))]
    return motif



def implant_motif_seq(seq,motif):
    place_injection_motif=int(random.uniform(0,len(seq)))
    return seq[:place_injection_motif]+motif+seq[place_injection_motif:]




def motif_low_complexe_valide(motif,minrep,taille_motif):
    for mod in range(0,taille_motif):
        tmp_motif=motif[mod:]
        lettre_actu=tmp_motif[:taille_motif]
        cpt=1
        for i in range(taille_motif,len(tmp_motif),taille_motif):
                if lettre_actu==tmp_motif[i:i+taille_motif]:
                    cpt+=1
                
                    if (cpt>=minrep):
                        return False
                else:
                    lettre_actu=tmp_motif[i:i+taille_motif]
                    cpt=1
    return True
                

assert(motif_low_complexe_valide("ATGC",2,2)==True)
assert(motif_low_complexe_valide("GATATATGC",3,2)==False)
assert(motif_low_complexe_valide("ATATATGC",3,2)==False)
assert(motif_low_complexe_valide("ATAAGC",2,1)==False)
assert(motif_low_complexe_valide("ATGC",2,1)==True)
assert(motif_low_complexe_valide("ATTGC",2,1)==False)
assert(motif_low_complexe_valide("ATGC",50,1)==True)

                
def removeLowComplexe(sequences, minrep,taille_motif):
    res=[]
    
    for seq in sequences:
        res_seq=""
        for i in range(0,len(seq)-k,k):
            if motif_low_complexe_valide(seq[i:i+k],minrep,taille_motif):
                res_seq+=seq[i:i+k]
        
        if not res_seq=="":
            res+=[res_seq]
        
    
    return res

def implantMotifVar(k, v, t, n):
       
    sequences=generateRandomSequences(n, t)
    
    
    res=[]
    motif=generateMotif(k,v)
    
    for seq in sequences:
        res+=["".join(implant_motif_seq(seq,motif))]
    
    return "".join(motif),res



In [2]:
#generate and implant variavel motifs
motif_implante,sequences = implantMotifVar(k, v, t, n)

print("motif implanté: ",motif_implante,"\n\n")
print("séquences obtenues :\n\n",sequences,"\n\n")

motif implanté:  GCAGCTT 


séquences obtenues :

 ['GTGGCAGCTTCGACACGAGAACTGGCTGACGTCCCCTGATGTGTAAGTAAACAGTGT', 'AATTGAACGGCACTCTGTCCCTGCAGCTTCTATCCGCGGGCCGGTTGTTTCAACCGG', 'TGGCAGCTTAGACGAACTCCAAGGTACTCTCCCCCTCATCCGTTACGCCAAAACTTT', 'CAAACTTCCGTAACAGTGACGTGGGGCGCAGCTTCGCAATCTCCGATATGCTTCACG', 'GATTTCCATAGGTCTCCTGACAGTGTGCAGCTTTTGGTAATCGTGAAATGCAGAGCA', 'CTACATAACAGAGCAGCTTTGGCGACTAAAGATCCGTTATCTTAGCGGGATTATCGG', 'GCAGCTTGTGAACGGGCCCTCAATTTTTACGTGCGCGTTTCTGCATTAGCAGACGTA', 'AGGATTTTGCAGCTTGATCTGTAGGGTCAGGATCATGTTTCTGCGAGTACATTCGCA', 'AGATATATTATGGCAGCTTCTCAACTAGCACGGCGCGAGAGAGATAGTACTGGTTTT', 'GCCTTCGCTTGGCAGCTTAACTGTCAATATTAAAGGAGAGCCTCTGCAGGCGCGGTT', 'GTGTGCAGCTTTTTTATAGGACCCAGGCGATCGGACCGGCCGCGGTCTGATTACGAC', 'GTCCTGCAAATGCGATATCAGACAAGAGGCAGCTTGGCCAGGCCAGGCGGACCGTGA', 'CTGGCTCTCCGCTACATATCACCGAGGGAGGATTTACCACCTTTATGCAGCTTAGCA', 'ATCTCTCATCCAACGAAATTTCCGCCAGCAATAAATAAATTACCCGCAGCTTCCCCC', 'AAACGCCACACCGCATTTCAAAAAGCGACCTCAGAAAGGAGATCTGCAGCTTTCAGA', 'CACAGGTGAAGGTCGCAGCGGTTTACACAGCA

In [3]:
#creating vector s
#Get t random positions from 0 to n - k
def generateRandomS(sequences, taille_motif , nombre_de_positions):
    
    return [int(random.uniform(0,n-taille_motif)) for k in range(0,nombre_de_positions)] 

s = generateRandomS(sequences, k , t)


print("positions de départ: ",s)    

positions de départ:  [28, 15, 19, 42, 10, 30, 14, 6, 23, 41, 30, 11, 30, 5, 33, 25, 14, 21, 28, 41]


In [4]:
#extract sequences from seqs
def extractSeqs(s, seqs):    
    return (list(map(lambda s_elem,seqs_elem : "".join(seqs_elem[s_elem:s_elem+k])  ,s,seqs)))

motifs = extractSeqs(s, sequences)
print("motifs obtenus:\n\n",motifs,"\n\n")
    
dico_nucl={"A":0,"T":1,"G":2,"C":3}


        
        
        
#on suppose que les motifs sont tous de la même taille
def profile(motifs):
    
    taille_motif=len(motifs[0])
    #initialisation de la matrice
    PWM = np.ones((4, taille_motif))

    #ajout des informations de chaque motif a la matrice
    for tmp_motif in motifs:
        for i in range(0,taille_motif):
            PWM[dico_nucl[tmp_motif[i]]][i]+=1
            
    return PWM

mat_profile=profile(motifs)

print("matrice de profil obtenue :\n\n",mat_profile)

motifs obtenus:

 ['ACGTCCC', 'TGTCCCT', 'CAAGGTA', 'CCGATAT', 'GGTCTCC', 'GATCCGT', 'GGCCCTC', 'TTGCAGC', 'ACTAGCA', 'CTCTGCA', 'TCGGACC', 'GCGATAT', 'GATTTAC', 'TCATCCA', 'GAAAGGA', 'CACAGCA', 'AGCTTTG', 'CTCACTG', 'CCGCAGA', 'TGGGTGA'] 


matrice de profil obtenue :

 [[4. 6. 4. 7. 4. 4. 9.]
 [6. 4. 6. 6. 7. 5. 5.]
 [7. 6. 8. 4. 6. 6. 3.]
 [7. 8. 6. 7. 7. 9. 7.]]


In [5]:
#test

test_profile=profile(['A','T','C'])
#print(test_profile)

In [6]:
def profile_into_PWM(profile):
    #on suppose que toutes les séquences ont la même longueur
    return list(map(lambda mat_pro:(list(map(lambda case:case/(t+4),mat_pro))),profile))


mat_PWM=profile_into_PWM(mat_profile)
print("mat_PWM obtenue :\n\n",profile_into_PWM(mat_profile))



mat_PWM obtenue :

 [[0.16666666666666666, 0.25, 0.16666666666666666, 0.2916666666666667, 0.16666666666666666, 0.16666666666666666, 0.375], [0.25, 0.16666666666666666, 0.25, 0.25, 0.2916666666666667, 0.20833333333333334, 0.20833333333333334], [0.2916666666666667, 0.25, 0.3333333333333333, 0.16666666666666666, 0.25, 0.25, 0.125], [0.2916666666666667, 0.3333333333333333, 0.25, 0.2916666666666667, 0.2916666666666667, 0.375, 0.2916666666666667]]


In [7]:
dico_nucl={"A":0,"T":1,"G":2,"C":3}

def probability(index_start,tmp_PWM, seq):
    proba=1
    taille_motif=len(seq)
    
    if (taille_motif+index_start>len(tmp_PWM[0])):
        return 0
    
    for a in range(0,taille_motif):
        proba=proba*tmp_PWM[dico_nucl[seq[a]]][a+index_start]
    
    return proba
        

In [8]:
#test
print(probability(0,mat_PWM,["A","T"]))

0.027777777777777776


In [9]:
def pMostProbkmer(P, k, sequence):
    maxProb = 0
    s = 0 # position du k-mer le plus probable dans la sequence
    
    range_taille_motifs=len(sequence)-k
    for index in range(0,range_taille_motifs):
        tmp_proba=probability(index,P,sequence[index:index+k])
        
        if (maxProb<tmp_proba):
            s=index
            maxProb=tmp_proba

    return s



In [10]:
#test
s = pMostProbkmer(mat_PWM, k, "GCCGGATACT")

#si k=7, le resultat attendu est 0
assert(s==0)


In [11]:
mat_profile_sequences=profile(sequences)
print("longueur de la mat profil des séquences: ",len(mat_profile_sequences[0])," len des séquences : ",len(sequences[0]),"\n\n")
#print("matrice de profil des séquences : \n",mat_profile_sequences)

longueur de la mat profil des séquences:  57  len des séquences :  57 




In [12]:
def getNewS( mat_profile, sequences):    
    res=[]
    mat_PWM=profile_into_PWM(mat_profile)
    
    for seq_elem in sequences:
        res+=[pMostProbkmer(mat_PWM,k,seq_elem)]
    
    
    return res

In [13]:
start_probables_sequences = getNewS( mat_profile_sequences , sequences)
print ("start positions des motifs les plus probables :\n\n",start_probables_sequences,"\n\n")

start positions des motifs les plus probables :

 [37, 31, 14, 35, 7, 11, 39, 38, 13, 42, 48, 14, 40, 47, 47, 47, 12, 14, 19, 42] 




In [14]:
import numpy as np

In [15]:
def changedProfile(P1, P2):
    return not np.array_equal(P1, P2)

In [16]:
assert(changedProfile("ABC","ABC")==0)
assert(changedProfile("ABC","ACC")==1)

In [33]:
def getScore(P,start,taille_motif):
    sc = 0
    for i in range(start,start+taille_motif):
         if i < len(P[0]):
                sc+=max(P[0][i],P[1][i],P[2][i],P[3][i])
    return sc

def getScoreAllPositions(P,starts,taille_motif):
    sc = 0
    for start in starts:
        for i in range(start,start+taille_motif):
            if i < len(P[0]):
                sc+=max(P[0][i],P[1][i],P[2][i],P[3][i])
    return sc

def getScoreListe(P,taille_motif,liste):
    return [getScore( P, start, taille_motif ) for start in liste ]


print ("Score des motifs les plus probables de la séquence:\n\n",getScoreListe(mat_profile_sequences,k,start_probables_sequences),"\n\n")

Score des motifs les plus probables de la séquence:

 [72.0, 63.0, 71.0, 70.0, 72.0, 74.0, 73.0, 72.0, 74.0, 71.0, 71.0, 71.0, 73.0, 73.0, 73.0, 73.0, 73.0, 71.0, 67.0, 71.0] 




In [18]:

def GreedyProfileMotifSearch(sequences, mat_profile, t, n, k):
    s = generateRandomS(sequences, k, t)
    bestScore = 0
    score = getScoreAllPositions(mat_profile, s, k)
    while score > bestScore:
        bestScore = score
        for j in range(1,t):
            s[j] = pMostProbkmer(mat_profile,k,sequences[j])
        score = getScoreAllPositions(mat_profile, s, k)
    
    return s, bestScore

        
s, bestScore = GreedyProfileMotifSearch(sequences, mat_profile_sequences, t, n, k)   
motifs = extractSeqs(s, sequences)
motifs = [''.join(m) for m in motifs]
print (motifs)
print(motif_implante in motifs)

['GGCTGAC', 'ATCCGCG', 'AACTCCA', 'GCAATCT', 'ATAGGTC', 'AGCAGCT', 'TCTGCAT', 'TTCTGCG', 'CAGCTTC', 'TCTGCAG', 'GATTACG', 'ATATCAG', 'CTTTATG', 'AGCTTCC', 'AGCTTTC', 'ATACTTC', 'GCAGCTT', 'ATCATCA', 'AGCAGAC', 'GGGTGAG']
True


In [19]:
def GreedyProfileMotifSearchIte(sequences, mat_profile, t, n, k, It):
    scores = []
    positions = []
    for i in range(It):
        s, score = GreedyProfileMotifSearch(sequences, mat_profile, t,n, k)
        scores.append(score)
        positions.append(s)
    j = scores.index(max(scores))
    return scores[j], positions[j]
    
bestScore, s = GreedyProfileMotifSearchIte(sequences,mat_profile_sequences, t, n, k, 100)
print (bestScore, s)
motifs = extractSeqs(s, sequences)
print (motifs)
print(motif_implante in motifs)

1262.0 [13, 31, 14, 35, 7, 11, 39, 38, 13, 42, 48, 14, 40, 47, 47, 47, 12, 14, 19, 42]
['CACGAGA', 'ATCCGCG', 'AACTCCA', 'GCAATCT', 'ATAGGTC', 'AGCAGCT', 'TCTGCAT', 'TTCTGCG', 'CAGCTTC', 'TCTGCAG', 'GATTACG', 'ATATCAG', 'CTTTATG', 'AGCTTCC', 'AGCTTTC', 'ATACTTC', 'GCAGCTT', 'ATCATCA', 'AGCAGAC', 'GGGTGAG']
True


In [21]:
def getRandomFixePositions(taille_liste, n_max):
    
   
    return [int(random.uniform(0,n_max)) for u in range(0,taille_liste)] 

lR = getRandomFixePositions(7, 4)
#lR.sort()
#print (lR)

def generateKey(positions, motif):

    return "".join(map(lambda tmp_pos: motif[tmp_pos]  ,positions))
   



In [22]:
k=7 #taille de motif
v=4 #nb de positions variable dans le motif
t=20 #nb de sequences
n=50 #longuer des sequence

def randomProjection(DNA,t,n,k,v):
    Bucket  = dict()
    motifs_res  = set()
    
    for j in range(0,len(DNA)):
        for i in range(0,n-k):
        
            tmp_motif="".join(DNA[j][i:i+k])
       
            motifs_res.add(tmp_motif)
        
            positions=getRandomFixePositions( v , k )
        
            key=generateKey( positions , tmp_motif )
                
            if key in Bucket:
                Bucket [ key ] += [tmp_motif]
            else:
                Bucket [ key ] = [tmp_motif]
        
    return Bucket, motifs_res

#motifsSort = sorted(motifs, reverse=True, key=motifs.get)
motifs, motifsSeq = randomProjection(sequences, t , n , k , v)
print (" le motif implanté a été trouvé? : ",motif_implante,motif_implante in motifsSeq)



 le motif implanté a été trouvé? :  GCAGCTT True


In [23]:
import operator

In [24]:
k=7 #taille de motif
v=4 #nb de positions variable dans le motif
t=20 #nb de sequences
n=50 #longuer des sequence

def evaluation_buckets(mat_profil,dico_buckets,N_meilleurs_bucket,taille_motif):
    best_score=0
    best_motif=""
    cpt_motif_best_score=0
    cpt=0
    for id_bucket in dico_buckets:
        tmp_bucket=dico_buckets[id_bucket]
        for i in tmp_bucket:
        
            tmp_score=getScore(mat_profil,i[0],taille_motif)
        
            if tmp_score>best_score:
                best_score=tmp_score
                best_motif=i[1]
                print("\t",best_motif,best_score)
                cpt_motif_best_score=1
            
            if tmp_score==best_score:
                cpt_motif_best_score+=1
            
        if (cpt>=N_meilleurs_bucket):
            return (best_score,best_motif,cpt_motif_best_score)
        
        cpt+=1
    
    
    return best_score,best_motif,cpt_motif_best_score

def randomProjIt(DNA,t,n,k,v, It,N_buckets):
    
    profile_mat=profile(sequences)

    
    
    Bucket  = dict()
    motifs_res  = set()
    
    for cpt in range (0,It):
        
        
        
        for j in range(0,len(DNA)):
            for i in range(0,n-k):
        
                tmp_motif="".join(DNA[j][i:i+k])
       
                motifs_res.add(tmp_motif)
            
                positions=getRandomFixePositions( v , k )
                
                key=generateKey( positions , tmp_motif )
                
                if key in Bucket:
                    Bucket [ key ] += [(i,tmp_motif)]
                else:
                    Bucket [ key ] = [(i,tmp_motif)]
                
            
    #tri du dictionnaire en fonction des Bucket les plus remplis
    Bucket=dict( (a,Bucket[a]) for a in (sorted(Bucket, key=lambda k: len(Bucket[k]), reverse=True)))
    print("best motifs candidats:\n")
    best_score,best_motif,cpt_best_score=evaluation_buckets(profile_mat,Bucket,N_buckets,k)
    print("\n\n\n")
    return best_score,best_motif,cpt_best_score

best_score,best_motif,cpt_best_score =randomProjIt(sequences, t , n , k , v,10,5)

print("motif implanté :",motif_implante," ,Best motif trouvé :",best_motif," ,score :",best_score," ,nombre de motifs ayant le meilleur score:",cpt_best_score)

#for k in Bucket:
#   print(len(Bucket[k]))

best motifs candidats:

	 GGCAGCT 55.0
	 GCAGCTT 58.0
	 CCCTGCA 59.0
	 GCGGGCC 62.0
	 TCCTGAC 63.0
	 CCGCTAC 64.0
	 TCTGTCC 66.0




motif implanté : GCAGCTT  ,Best motif trouvé : TCTGTCC  ,score : 66.0  ,nombre de motifs ayant le meilleur score: 27


In [25]:
bb={"b":[9,1],"c":[1,2,1],"a":[40,0,0,0,0]}
print(dict( (a,bb[a]) for a in (sorted(bb, key=lambda k: len(bb[k]), reverse=True))))

{'a': [40, 0, 0, 0, 0], 'c': [1, 2, 1], 'b': [9, 1]}
